apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-currency-exchange
  namespace: crypto-currency-exchange
  labels:
    app.kubernetes.io/name: crypto-currency-exchange
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: crypto-currency-exchange
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crypto-currency-exchange
    spec:
      # imagePullSecrets:
      #   - name: regcred
      containers:
      - name: crypto-currency-exchange
        image: docker.io/alimehr75/crypto-currency-exchange:1b52684
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1Gi
        envFrom:
          - configMapRef:
              name: cce-configmap
              optional: false
          - secretRef:
              name: cce-secret
              optional: false
